import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FAccordionStyle accordionStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FAccordionStyle(
  titleTextStyle: FWidgetStateMap({
    WidgetState.hovered | WidgetState.pressed: typography.base.copyWith(
      fontWeight: FontWeight.w500,
      color: const Color(PRIMARY_COLOR),
      decoration: TextDecoration.underline,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.any: typography.base.copyWith(
      fontWeight: FontWeight.w500,
      color: const Color(PRIMARY_COLOR),
      fontFamily: FONT_FAMILY,
    ),
  }),
  childTextStyle: typography.sm.copyWith(
    color: colors.foreground,
    fontFamily: FONT_FAMILY,
  ),
  iconStyle: FWidgetStateMap.all(
    IconThemeData(color: const Color(PRIMARY_COLOR), size: 20),
  ),
  focusedOutlineStyle: style.focusedOutlineStyle,
  dividerStyle: FDividerStyle(color: colors.border, padding: EdgeInsets.zero),
  tappableStyle: style.tappableStyle,
  titlePadding: const EdgeInsets.symmetric(vertical: 15),
  childPadding: const EdgeInsets.only(bottom: 15),
);
