import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FAlertStyle alertStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  Color backgroundColor = const Color(PRIMARY_COLOR), // 使用自定义主色
  Color foregroundColor = Colors.white,
}) => FAlertStyle(
  decoration: BoxDecoration(
    borderRadius: style.borderRadius,
    color: backgroundColor,
    border: Border.all(color: colors.border, width: style.borderWidth),
  ),
  padding: const EdgeInsets.all(16),
  iconStyle: IconThemeData(color: foregroundColor, size: 20),
  titleTextStyle: typography.base.copyWith(
    color: foregroundColor,
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.w500,
  ),
  subtitleTextStyle: typography.sm.copyWith(
    color: foregroundColor.withValues(alpha: 0.8),
    fontFamily: FONT_FAMILY,
  ),
);
