import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FAvatarStyle avatarStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FAvatarStyle(
  backgroundColor: Color(PRIMARY_COLOR), // 使用自定义主色
  foregroundColor: Colors.white,
  textStyle: typography.base.copyWith(
    color: Colors.white,
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.w500,
  ),
  fadeInDuration: const Duration(milliseconds: 300),
);
