import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FBadgeStyle badgeStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  Color backgroundColor = const Color(PRIMARY_COLOR), // 使用自定义主色
  Color foregroundColor = Colors.white,
}) => FBadgeStyle(
  decoration: BoxDecoration(
    borderRadius: BorderRadius.circular(9999),
    color: backgroundColor,
  ),
  contentStyle: FBadgeContentStyle(
    labelTextStyle: typography.xs.copyWith(
      color: foregroundColor,
      fontFamily: FONT_FAMILY,
      fontWeight: FontWeight.w500,
    ),
    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
  ),
);
