import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FBottomNavigationBarStyle bottomNavigationBarStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FBottomNavigationBarStyle(
  decoration: BoxDecoration(
    color: colors.background,
    border: Border(
      top: BorderSide(color: colors.border, width: style.borderWidth),
    ),
  ),
  padding: const EdgeInsets.symmetric(horizontal: 16),
  itemStyle: FBottomNavigationBarItemStyle(
    iconStyle: FWidgetStateMap({
      WidgetState.selected: IconThemeData(
        color: Color(PRIMARY_COLOR),
        size: 24,
      ), // 使用自定义主色
      WidgetState.any: IconThemeData(color: colors.mutedForeground, size: 24),
    }),
    textStyle: FWidgetStateMap({
      WidgetState.selected: typography.sm.copyWith(
        color: Color(PRIMARY_COLOR), // 使用自定义主色
        fontFamily: FONT_FAMILY,
        fontWeight: FontWeight.w500,
      ),
      WidgetState.any: typography.sm.copyWith(
        color: colors.mutedForeground,
        fontFamily: FONT_FAMILY,
      ),
    }),
    padding: const EdgeInsets.symmetric(vertical: 8),
    spacing: 4,
    tappableStyle: FTappableStyle(),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: Color(PRIMARY_COLOR), // 使用自定义主色
      borderRadius: BorderRadius.zero,
    ),
  ),
);
