import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FBreadcrumbStyle breadcrumbStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FBreadcrumbStyle(
  textStyle: FWidgetStateMap({
    WidgetState.selected &
        (WidgetState.hovered | WidgetState.pressed): typography.sm.copyWith(
      fontWeight: FontWeight.w400,
      color: colors.foreground,
      decoration: TextDecoration.underline,
    ),
    WidgetState.selected: typography.sm.copyWith(
      fontWeight: FontWeight.w400,
      color: colors.foreground,
    ),
    WidgetState.hovered | WidgetState.pressed: typography.sm.copyWith(
      fontWeight: FontWeight.w400,
      color: colors.primary,
      decoration: TextDecoration.underline,
    ),
    WidgetState.any: typography.sm.copyWith(
      fontWeight: FontWeight.w400,
      color: colors.mutedForeground,
    ),
  }),
  iconStyle: IconThemeData(color: colors.mutedForeground, size: 16),
  tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
  focusedOutlineStyle: style.focusedOutlineStyle,
  padding: const EdgeInsets.symmetric(horizontal: 5),
);
