import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FCardStyle cardStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FCardStyle(
  decoration: BoxDecoration(
    borderRadius: style.borderRadius,
    color: colors.background,
    border: Border.all(color: colors.border, width: style.borderWidth),
    boxShadow: style.shadow,
  ),
  contentStyle: FCardContentStyle(
    imageSpacing: 16,
    subtitleSpacing: 4,
    titleTextStyle: typography.lg.copyWith(
      color: colors.foreground,
      fontFamily: FONT_FAMILY,
      fontWeight: FontWeight.w600,
    ),
    subtitleTextStyle: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
    padding: const EdgeInsets.all(16),
  ),
);
