import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FCheckboxStyle checkboxStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FCheckboxStyle(
  tappableStyle: style.tappableStyle,
  focusedOutlineStyle: FFocusedOutlineStyle(
    color: Color(PRIMARY_COLOR), // 使用自定义主色
    borderRadius: style.borderRadius,
  ),
  size: 20,
  iconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.disable(colors.primaryForeground),
      size: 16,
    ),
    WidgetState.any: IconThemeData(color: Colors.white, size: 16),
  }),
  decoration: FWidgetStateMap({
    WidgetState.selected: BoxDecoration(
      borderRadius: style.borderRadius,
      color: Color(PRIMARY_COLOR), // 使用自定义主色
      border: Border.all(color: Color(PRIMARY_COLOR), width: style.borderWidth),
    ),
    WidgetState.disabled: BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.muted,
      border: Border.all(color: colors.border, width: style.borderWidth),
    ),
    WidgetState.any: BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.background,
      border: Border.all(color: colors.border, width: style.borderWidth),
    ),
  }),
  labelPadding: const EdgeInsets.only(left: 8),
  descriptionPadding: const EdgeInsets.only(top: 4),
  errorPadding: const EdgeInsets.only(top: 4),
  childPadding: const EdgeInsets.only(top: 8),
  labelTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.base.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.any: typography.base.copyWith(
      color: colors.foreground,
      fontFamily: FONT_FAMILY,
    ),
  }),
  descriptionTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.any: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
  }),
  errorTextStyle: typography.sm.copyWith(
    color: colors.error,
    fontFamily: FONT_FAMILY,
  ),
);
