import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FDividerStyle dividerStyle({required FColors colors, required FStyle style}) =>
    FDividerStyle(
      color: colors.border,
      width: style.borderWidth,
      padding: const EdgeInsets.symmetric(vertical: 8),
    );
