import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FFormFieldStyle formFieldStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FFormFieldStyle(
  labelTextStyle: FWidgetStateMap({
    WidgetState.error: typography.sm.copyWith(
      color: colors.error,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.disabled: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.any: typography.sm.copyWith(
      color: colors.foreground,
      fontFamily: FONT_FAMILY,
      fontWeight: FontWeight.w500,
    ),
  }),
  descriptionTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
    WidgetState.any: typography.sm.copyWith(
      color: colors.mutedForeground,
      fontFamily: FONT_FAMILY,
    ),
  }),
  errorTextStyle: typography.sm.copyWith(
    color: colors.error,
    fontFamily: FONT_FAMILY,
  ),
);
