import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:forui/forui.dart';

import 'const.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FHeaderStyle headerStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FHeaderStyle(
  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
  actionSpacing: 8,
  systemOverlayStyle: const SystemUiOverlayStyle(),
  titleTextStyle: typography.xl2.copyWith(
    color: colors.foreground,
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.w700,
  ),
  actionStyle: FHeaderActionStyle(
    iconStyle: FWidgetStateMap({
      WidgetState.any: IconThemeData(color: colors.foreground, size: 24),
    }),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: Color(PRIMARY_COLOR), // 使用自定义主色
      borderRadius: BorderRadius.zero,
    ),
    tappableStyle: FTappableStyle(),
  ),
);
