import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FLineCalendarStyle lineCalendarStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final focusedBorder = Border.all(
    color: colors.primary,
    width: style.borderWidth,
  );
  return FLineCalendarStyle(
    decoration: FWidgetStateMap({
      WidgetState.selected &
          (WidgetState.hovered | WidgetState.pressed) &
          WidgetState.focused: BoxDecoration(
        color: colors.hover(colors.primary),
        border: focusedBorder,
        borderRadius: style.borderRadius,
      ),
      WidgetState.selected &
          (WidgetState.hovered | WidgetState.pressed): BoxDecoration(
        color: colors.hover(colors.primary),
        borderRadius: style.borderRadius,
      ),
      WidgetState.selected & WidgetState.focused: BoxDecoration(
        color: colors.primary,
        border: focusedBorder,
        borderRadius: style.borderRadius,
      ),
      WidgetState.selected: BoxDecoration(
        color: colors.primary,
        borderRadius: style.borderRadius,
      ),
      (WidgetState.hovered | WidgetState.pressed) &
          WidgetState.focused: BoxDecoration(
        color: colors.secondary,
        border: focusedBorder,
        borderRadius: style.borderRadius,
      ),
      (WidgetState.hovered | WidgetState.pressed): BoxDecoration(
        color: colors.secondary,
        border: Border.all(color: colors.border),
        borderRadius: style.borderRadius,
      ),
      WidgetState.focused: BoxDecoration(
        color: colors.background,
        border: focusedBorder,
        borderRadius: style.borderRadius,
      ),
      WidgetState.any: BoxDecoration(
        color: colors.background,
        border: Border.all(color: colors.border),
        borderRadius: style.borderRadius,
      ),
    }),
    todayIndicatorColor: FWidgetStateMap({
      WidgetState.selected & (WidgetState.hovered | WidgetState.pressed): colors
          .hover(colors.primaryForeground),
      WidgetState.selected: colors.primaryForeground,
      (WidgetState.hovered | WidgetState.pressed): colors.hover(colors.primary),
      WidgetState.any: colors.primary,
    }),
    dateTextStyle: FWidgetStateMap({
      WidgetState.selected: typography.xl.copyWith(
        color: colors.primaryForeground,
        fontWeight: FontWeight.w500,
        height: 0,
      ),
      WidgetState.any: typography.xl.copyWith(
        color: colors.primary,
        fontWeight: FontWeight.w500,
        height: 0,
      ),
    }),
    weekdayTextStyle: FWidgetStateMap({
      WidgetState.selected: typography.xs.copyWith(
        color: colors.primaryForeground,
        fontWeight: FontWeight.w500,
        height: 0,
      ),
      WidgetState.any: typography.xs.copyWith(
        color: colors.mutedForeground,
        fontWeight: FontWeight.w500,
        height: 0,
      ),
    }),
    tappableStyle: style.tappableStyle,
    padding: const EdgeInsets.symmetric(horizontal: 6.5),
    contentEdgeSpacing: 15.5,
    contentSpacing: 2,
  );
}
