import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FPaginationStyle paginationStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FPaginationStyle(
  itemIconStyle: FWidgetStateMap.all(
    IconThemeData(color: colors.primary, size: 18),
  ),
  itemDecoration: FWidgetStateMap({
    WidgetState.selected &
        (WidgetState.hovered | WidgetState.pressed): BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.hover(colors.primary),
    ),
    WidgetState.selected: BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.primary,
    ),
    WidgetState.hovered: BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.border,
    ),
    WidgetState.any: BoxDecoration(
      borderRadius: style.borderRadius,
      color: colors.background,
    ),
  }),
  itemTextStyle: FWidgetStateMap({
    WidgetState.selected: typography.sm.copyWith(
      color: colors.primaryForeground,
    ),
    WidgetState.any: typography.sm.copyWith(color: colors.primary),
  }),
  ellipsisTextStyle: typography.sm.copyWith(color: colors.primary),
  actionTappableStyle: style.tappableStyle,
  pageTappableStyle: style.tappableStyle,
  focusedOutlineStyle: style.focusedOutlineStyle,
  itemPadding: const EdgeInsets.symmetric(horizontal: 2),
  itemConstraints: const BoxConstraints.tightFor(width: 40.0, height: 40.0),
);
