import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FSelectSectionStyle selectSectionStyle({
  required FColors colors,
  required FStyle style,
  required FTypography typography,
}) {
  const padding = EdgeInsetsDirectional.only(
    start: 11,
    top: 7.5,
    bottom: 7.5,
    end: 6,
  );
  final iconStyle = FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.disable(colors.primary),
      size: 15,
    ),
    WidgetState.any: IconThemeData(color: colors.primary, size: 15),
  });
  final textStyle = FWidgetStateMap({
    WidgetState.disabled: typography.sm.copyWith(
      color: colors.disable(colors.primary),
    ),
    WidgetState.any: typography.sm.copyWith(color: colors.primary),
  });
  return FSelectSectionStyle(
    labelTextStyle: FWidgetStateMap({
      WidgetState.disabled: typography.sm.copyWith(
        color: colors.disable(colors.primary),
        fontWeight: FontWeight.w600,
      ),
      WidgetState.any: typography.sm.copyWith(
        color: colors.primary,
        fontWeight: FontWeight.w600,
      ),
    }),
    dividerColor: FWidgetStateMap.all(colors.border),
    dividerWidth: style.borderWidth,
    itemStyle: FItemStyle(
      backgroundColor: FWidgetStateMap.all(null),
      decoration: FWidgetStateMap({
        ~WidgetState.disabled &
            (WidgetState.focused |
                WidgetState.hovered |
                WidgetState.pressed): BoxDecoration(
          color: colors.secondary,
          borderRadius: style.borderRadius,
        ),
      }),
      contentStyle: _itemContentStyle(colors: colors, typography: typography)
          .copyWith(
            padding: padding,
            prefixIconStyle: iconStyle,
            prefixIconSpacing: 10,
            titleTextStyle: textStyle,
            titleSpacing: 4,
            subtitleTextStyle: FWidgetStateMap({
              WidgetState.disabled: typography.xs.copyWith(
                color: colors.disable(colors.mutedForeground),
              ),
              WidgetState.any: typography.xs.copyWith(
                color: colors.mutedForeground,
              ),
            }),
            suffixIconStyle: FWidgetStateMap({
              WidgetState.disabled: IconThemeData(
                color: colors.disable(colors.primary),
                size: 15,
              ),
              WidgetState.any: IconThemeData(color: colors.primary, size: 15),
            }),
          ),
      rawItemContentStyle: FRawItemContentStyle(
        padding: padding,
        prefixIconStyle: iconStyle,
        childTextStyle: textStyle,
      ),
      tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
      focusedOutlineStyle: null,
    ),
  );
}

FItemContentStyle _itemContentStyle({
  required FColors colors,
  required FTypography typography,
}) => FItemContentStyle(
  prefixIconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.disable(colors.primary),
      size: 15,
    ),
    WidgetState.any: IconThemeData(color: colors.primary, size: 15),
  }),
  titleTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.sm.copyWith(
      color: colors.disable(colors.primary),
    ),
    WidgetState.any: typography.sm,
  }),
  subtitleTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.xs.copyWith(
      color: colors.disable(colors.mutedForeground),
    ),
    WidgetState.any: typography.xs.copyWith(color: colors.mutedForeground),
  }),
  detailsTextStyle: FWidgetStateMap({
    WidgetState.disabled: typography.xs.copyWith(
      color: colors.disable(colors.mutedForeground),
    ),
    WidgetState.any: typography.xs.copyWith(color: colors.mutedForeground),
  }),
  suffixIconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.disable(colors.mutedForeground),
      size: 15,
    ),
    WidgetState.any: IconThemeData(color: colors.mutedForeground, size: 15),
  }),
  padding: const EdgeInsetsDirectional.only(
    start: 11,
    top: 7.5,
    bottom: 7.5,
    end: 6,
  ),
  prefixIconSpacing: 10,
  titleSpacing: 3,
  middleSpacing: 4,
  suffixIconSpacing: 5,
);
