import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FSidebarItemStyle sidebarItemStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FSidebarItemStyle(
  textStyle: FWidgetStateMap({
    WidgetState.disabled: typography.base.copyWith(
      color: colors.mutedForeground,
      height: 1,
      overflow: TextOverflow.ellipsis,
    ),
    WidgetState.any: typography.base.copyWith(
      color: colors.foreground,
      height: 1,
      overflow: TextOverflow.ellipsis,
    ),
  }),
  iconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.mutedForeground,
      size: 16,
    ),
    WidgetState.any: IconThemeData(color: colors.foreground, size: 16),
  }),
  collapsibleIconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.mutedForeground,
      size: 16,
    ),
    WidgetState.any: IconThemeData(color: colors.foreground, size: 16),
  }),
  backgroundColor: FWidgetStateMap({
    WidgetState.disabled: Colors.transparent,
    WidgetState.selected | WidgetState.hovered | WidgetState.pressed: colors
        .hover(colors.secondary),
    WidgetState.any: Colors.transparent,
  }),
  borderRadius: style.borderRadius,
  tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
  focusedOutlineStyle: style.focusedOutlineStyle.copyWith(spacing: 0),
  iconSpacing: 8,
  collapsibleIconSpacing: 8,
  childrenSpacing: 2,
  childrenPadding: const EdgeInsets.only(left: 26, top: 2),
  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
  motion: const FSidebarItemMotion(),
);
