import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'accordion_style.dart';
import 'alert_style.dart';
import 'autocomplete_style.dart';
import 'avatar_style.dart';
import 'badge_style.dart';
import 'bottom_navigation_bar_style.dart';
import 'breadcrumb_style.dart';
import 'button_style.dart';
import 'calendar_style.dart';
import 'card_style.dart';
import 'checkbox_style.dart';
import 'circular_progress_style.dart';
import 'date_field_style.dart';
import 'determinate_progress_style.dart';
import 'dialog_style.dart';
import 'divider_style.dart';
import 'form_field_style.dart';
import 'header_style.dart';
import 'item_group_style.dart';
import 'item_style.dart';
import 'label_styles.dart';
import 'line_calendar_style.dart';
import 'modal_sheet_style.dart';
import 'multi_select_style.dart';
import 'pagination_style.dart';
import 'picker_style.dart';
import 'popover_style.dart';
import 'popover_menu_style.dart';
import 'progress_style.dart';
import 'radio_style.dart';
import 'resizable_style.dart';
import 'scaffold_style.dart';
import 'select_style.dart';
import 'select_group_style.dart';
import 'select_menu_tile_style.dart';
import 'sidebar_style.dart';
import 'slider_styles.dart';
import 'switch_style.dart';
import 'tabs_style.dart';
import 'text_field_style.dart';
import 'tile_style.dart';
import 'tile_group_style.dart';
import 'time_field_style.dart';
import 'time_picker_style.dart';
import 'toast_style.dart';
import 'toaster_style.dart';
import 'tooltip_style.dart';
import 'const.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FThemeData get zincLight {
  const colors = FColors(
    brightness: Brightness.light,
    barrier: Color(0x33000000),
    background: Color(0xFFFFFFFF),
    foreground: Color(0xFF09090B),
    primary: Color(PRIMARY_COLOR), // 使用自定义主色
    primaryForeground: Color(0xFFFAFAFA),
    secondary: Color(0xFFF4F4F5),
    secondaryForeground: Color(0xFF18181B),
    muted: Color(0xFFF4F4F5),
    mutedForeground: Color(0xFF71717A),
    destructive: Color(0xFFEF4444),
    destructiveForeground: Color(0xFFFAFAFA),
    error: Color(0xFFEF4444),
    errorForeground: Color(0xFFFAFAFA),
    border: Color(0xFFE4E4E7),
    systemOverlayStyle: const SystemUiOverlayStyle(),
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    accordionStyle: accordionStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    autocompleteStyle: autocompleteStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    alertStyles: FAlertStyles(
      primary: alertStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: Color(PRIMARY_COLOR), // 使用自定义主色
        foregroundColor: Colors.white,
      ),
      destructive: alertStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: const Color(0xFFEF4444),
        foregroundColor: Colors.white,
      ),
    ),
    avatarStyle: avatarStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    badgeStyles: FBadgeStyles(
      primary: badgeStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: Color(PRIMARY_COLOR), // 使用自定义主色
        foregroundColor: Colors.white,
      ),
      secondary: badgeStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: const Color(0xFFF4F4F5),
        foregroundColor: const Color(0xFF18181B),
      ),
      outline: badgeStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: Colors.transparent,
        foregroundColor: Color(PRIMARY_COLOR), // 使用自定义主色
      ),
      destructive: badgeStyle(
        colors: colors,
        typography: typography,
        style: style,
        backgroundColor: const Color(0xFFEF4444),
        foregroundColor: Colors.white,
      ),
    ),
    bottomNavigationBarStyle: bottomNavigationBarStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    breadcrumbStyle: breadcrumbStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    buttonStyles: FButtonStyles(
      primary: primaryButtonStyle(
        colors: colors,
        typography: typography,
        style: style,
      ),
      secondary: secondaryButtonStyle(
        colors: colors,
        typography: typography,
        style: style,
      ),
      destructive: destructiveButtonStyle(
        colors: colors,
        typography: typography,
        style: style,
      ),
      outline: outlineButtonStyle(
        colors: colors,
        typography: typography,
        style: style,
      ),
      ghost: ghostButtonStyle(
        colors: colors,
        typography: typography,
        style: style,
      ),
    ),
    calendarStyle: calendarStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    cardStyle: cardStyle(colors: colors, typography: typography, style: style),
    checkboxStyle: checkboxStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    circularProgressStyle: circularProgressStyle(colors: colors),
    dateFieldStyle: dateFieldStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    determinateProgressStyle: determinateProgressStyle(
      colors: colors,
      style: style,
    ),
    dialogStyle: dialogStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    dividerStyles: FDividerStyles(
      horizontalStyle: dividerStyle(colors: colors, style: style),
      verticalStyle: dividerStyle(colors: colors, style: style),
    ),
    // headerStyles 参数已从下面删除，因为headerStyle返回FHeaderStyle而非FHeaderStyles
    itemStyle: itemStyle(colors: colors, typography: typography, style: style),
    // itemGroupStyle 参数已删除，不兼容
    labelStyles: labelStyles(style: style),
    lineCalendarStyle: lineCalendarStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    multiSelectStyle: multiSelectStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    modalSheetStyle: modalSheetStyle(colors: colors),
    paginationStyle: paginationStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    pickerStyle: pickerStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    popoverStyle: popoverStyle(colors: colors, style: style),
    popoverMenuStyle: popoverMenuStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    progressStyle: progressStyle(colors: colors, style: style),
    radioStyle: radioStyle(colors: colors, style: style),
    resizableStyle: resizableStyle(colors: colors, style: style),
    scaffoldStyle: scaffoldStyle(colors: colors, style: style),
    selectStyle: selectStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    // selectGroupStyle 参数已删除，不兼容
    // selectMenuTileStyle 参数已删除，不兼容
    sidebarStyle: sidebarStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    sliderStyles: sliderStyles(
      colors: colors,
      typography: typography,
      style: style,
    ),
    switchStyle: switchStyle(colors: colors, style: style),
    tabsStyle: tabsStyle(colors: colors, typography: typography, style: style),
    textFieldStyle: textFieldStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    // tileStyle 参数已删除，不兼容
    tileGroupStyle: tileGroupStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    timeFieldStyle: timeFieldStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    timePickerStyle: timePickerStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    toasterStyle: toasterStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
    tooltipStyle: tooltipStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
  );
}

FTypography _typography({
  required FColors colors,
  String defaultFontFamily = FONT_FAMILY, // 使用自定义字体常量
}) => FTypography(
  xs: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
  ),
  sm: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1.25,
  ),
  base: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1.5,
  ),
  lg: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1.75,
  ),
  xl: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1.75,
  ),
  xl2: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 2,
  ),
  xl3: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 2.25,
  ),
  xl4: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 2.5,
  ),
  xl5: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
  ),
  xl6: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
  ),
  xl7: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
  ),
  xl8: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
  ),
);

FStyle _style({
  required FColors colors,
  required FTypography typography,
}) => FStyle(
  formFieldStyle: formFieldStyle(
    colors: colors,
    typography: typography,
    style: FStyle.inherit(colors: colors, typography: typography),
  ),
  focusedOutlineStyle: FFocusedOutlineStyle(
    color: Color(PRIMARY_COLOR), // 使用自定义主色
    borderRadius: const BorderRadius.all(Radius.circular(8)),
  ),
  iconStyle: IconThemeData(color: Color(PRIMARY_COLOR), size: 20), // 使用自定义主色
  tappableStyle: FTappableStyle(),
  borderRadius: const FLerpBorderRadius.all(Radius.circular(8), min: 24),
  borderWidth: 1,
  pagePadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
  shadow: const [
    BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
  ],
);
